# -*- coding: utf-8 -*-
"""Imersão_dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rSAIvJy4qbfG2RTeRclf0KWwRzI0fgj8
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

dados = pd.read_csv('/Dados_Imersão - dados.csv')
avaliacoes = pd.read_csv('/Avaliacoes  - avaliacoes.csv')

dados.head(2)

dados.info()

dados.describe()

dados['actual_price'] = dados['actual_price'].str.replace('₹', '') #substituindo o simbolo da rupia para tipo numérico

dados['actual_price'] = dados['actual_price'].str.replace('.', '')
dados.head(2)

dados['actual_price'] = dados['actual_price'].str.replace(',', '.')

dados.head(2)

#substituindo o simbolo da rupia para tipo numérico
dados['actual_price'] = pd.to_numeric(dados['actual_price'])
dados.head()

#fazendo a mesma coisa para a coluna product_price
dados['product_price'] = dados['product_price'].str.replace('₹', '').str.replace('.', '').str.replace(',', '.')
dados['product_price'] = pd.to_numeric(dados['product_price'])
dados.head()

dados['rating'] = dados['rating'].str.replace(',', '.') #fazendo a mesma coisa para a coluna rating, transformando em dado numérico
dados['rating'] = pd.to_numeric(dados['rating'])

dados.info()

"""## Gráficos"""

rating_above_4_5 = dados[dados['rating'] > 4.5]
rating_counts = rating_above_4_5['rating'].value_counts().sort_index()

plt.figure(figsize=(10, 5))
sns.barplot(x=rating_counts.index, y=rating_counts.values)
plt.title('Contagem de Avaliações acima de 4.5')
plt.xlabel('Avaliação')
plt.ylabel('Contagem')
plt.show()

# Filtro 1: Valores até 50 rupias
filtro_ate_50 = dados[dados['actual_price'] <= 50]

# Filtro 2: Valores entre 50 e 500 rupias
filtro_50_500 = dados[(dados['actual_price'] > 50) & (dados['actual_price'] <= 500)]

# Filtro 3: Valores acima de 500 rupias
filtro_acima_500 = dados[dados['actual_price'] > 500]

# Contagem de produtos em cada faixa de valor
contagem = [len(filtro_ate_50), len(filtro_50_500), len(filtro_acima_500)]

# Rótulos para as fatias do gráfico
labels = ['Até 50 rupias', '50 - 500 rupias', 'Acima de 500 rupias']

# Cores para destacar o maior valor
colors = ['lightblue', 'lightgreen', 'lightcoral']

# Destacar a fatia maior
explode = (0.1, 0.1, 0.1)

# Criar o gráfico de pizza
plt.figure(figsize=(8, 6))
plt.pie(contagem, labels=labels, colors=colors, autopct='%1.1f%%', explode=explode, shadow=True, startangle=140)
plt.axis('equal')  # Para garantir que o gráfico de pizza seja uma forma de círculo

# Adicionar título
plt.title('Distribuição de Produtos por Faixa de Valor')

# Mostrar o gráfico
plt.show()

"""#Report"""

!pip install pandas-profiling

import pandas_profiling #biblioteca para criar report da base de dados

dados.profile_report()